name: on demand vim creation
on: workflow_dispatch
jobs:
  ondemand-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port $SSH_PORT
          END
        env:
          SSH_USER: ${{ secrets.PROXY_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PROXY_KEY }}
          SSH_HOST: ${{ secrets.PROXY_HOST }}
          SSH_PORT: ${{ secrets.PROXY_PORT }}

      - name: test
        run: ssh staging 'echo "i_was_here" > test.txt'