name: on demand vim creation
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ondemand]
jobs:
  ondemand-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/proxy.key
          chmod 600 ~/.ssh/proxy.key
          echo "$QEMU_KEY" > ~/.ssh/qemu.key
          chmod 600 ~/.ssh/qemu.key
          echo "$GIT_KEY" > ~/.ssh/git.key
          chmod 600 ~/.ssh/git.key
          cat >>~/.ssh/config <<END
          Host proxy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/proxy.key
            StrictHostKeyChecking no
            Port $SSH_PORT
          Host qemu
            HostName $QEMU_HOST
            IdentityFile ~/.ssh/qemu.key
            StrictHostKeyChecking no
            ProxyJump proxy
          END
        env:
          SSH_USER: ${{ secrets.PROXY_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PROXY_KEY }}
          SSH_HOST: ${{ secrets.PROXY_HOST }}
          SSH_PORT: ${{ secrets.PROXY_PORT }}
          QEMU_USER: ${{ secrets.USERNAME }}
          QEMU_HOST: ${{ secrets.HOST }}
          QEMU_KEY: ${{ secrets.KEY }}
          QEMU_PORT: ${{ secrets.HOST }}
          GIT_KEY: ${{ secrets.GIT_KEY }}
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.GIT_KEY }}' > id_rsa
          && ssh-keyscan github.com > known_hosts
          && chmod 600 id_rsa known_hosts
          && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
      

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Copy plan
        run : scp tfplan $QEMU_USER@qemu:/home/$QEMU_USER
        env:
          QEMU_USER: ${{ secrets.USERNAME }}
          QEMU_HOST: ${{ secrets.HOST }}
      
      - name: Terraform Apply
        id: apply
        run: terraform apply no-color -auto-approve